### ISSUE TITLE
Verification Email does not send

### ISSUE THREAD

**Issue by CuzImFl4mer** [NamelessMC/Nameless#2607] opened 2022-02-21 19:19 UTC
### Describe the issue

If some users will register on my forum, they don't get any Verification Mail. But if I send a Test Mail, it works fine! At the beginning it works fine..

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. User will register the account
2. User is waiting for a verification Mail
3. Verification Mail does not send to the Users Mail-Address

### Expected Behaviour

a verification Mail that sends to the user

**Comment by samerton** [comment] 2022-02-21 19:55
Possible duplicate of #2345

A couple of questions:
1. Could you try registering another account on the website yourself, to see if you get an email?
2. Does the "forgot password" email send?

If yes, then the issue will be that, for people that do not receive the email, their email provider is rejecting the email, or it is entering their junk/spam folder. In this case, this is not a Nameless issue.

**Comment by CuzImFl4mer** [comment] 2022-02-22 21:01
Nope, if I register a new Account it will not send any email. If I press "forgot password" it will send me no email too.

**Comment by PadowYT2** [comment] 2022-02-25 11:43
If you send a test message, will you get it on the mail?

**Comment by TeemoCell** [comment] 2022-03-15 15:34
If you use plesk, make sure you set `Outgoing mail mode` to `Send from domain IP addresses`
![image](https://user-images.githubusercontent.com/11705513/158413993-096a85e2-e8ec-42d4-b706-64d433f6845e.png)

**Comment by TeemoCell** [comment] 2022-03-15 15:35
Other thing you can try it use `Outgoing Email Address` only and disable `PHPMailer`.

**Closed** 2022-04-04 12:05 UTC
