### ISSUE TITLE
Posible New Feature./login

### ISSUE THREAD

**Issue by lockerecca** [NamelessMC/Nameless#92] opened 2016-02-07 19:58 UTC
i'm look your project and like me
but is not 100% compatible for my network :(

have a bungecord multiples 1.8.8 spigot servers etc but is Craked Server if Username not have a Premium or FalsePremium nickname can't Join on Forums
i have on my MySql one plugin of Auth called Logit ( abandoned ) the mysql table i think is the same of Authme 

i love if can Website can use my /login Database and if user not have email website tell for put and confirm

**Comment by samerton** [comment] 2016-02-07 21:32
You can disable the requirement for premium usernames in AdminCP -> Minecraft and then disable the "Enable UUID linking?" setting. This will allow anyone to register.

I'm planning on adding support for AuthMe in the future, however I doubt support for other similar plugins will be included.

**Comment by samerton** [comment] 2016-03-03 16:08
I'm going to close this issue as it's a duplicate of #6

**Closed by samerton** 2016-03-03 16:08 UTC
