### ISSUE TITLE
Custom page redirects give the 404 page

### ISSUE THREAD

**Issue by masonzettle** [NamelessMC/Nameless#1560] opened 2019-08-30 22:08 UTC
**Describe the issue**
Upon creating redirect custom pages for my donator store and vote links and attempting to use the page path I assign, the user is greeted to the 404 page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a custom page redirect
2. Go to the assigned page path
3. Encounter error

**Expected behaviour**
They should go to the assigned redirect link

**NamelessMC version (from AdminCP -> Overview)** 2.0.0-pr6

**Additional information**
Trying to create redirects through cPanel do not work either, unless the redirect path is on a subdomain (eg: vote.example.org/1 works, but example.org/vote1 does not).

**Comment by samerton** [comment] 2019-08-31 09:20
Does the page path start with a `/`, for example `/vote1`, and have you assigned permissions so everyone can see the page?

**Comment by masonzettle** [comment] 2019-08-31 17:14
Yes, it does start with a `/` and all groups have permission to view the page. Here is a screenshot of the custom page's settings:
![image](https://user-images.githubusercontent.com/37517085/64067111-1c11db80-cbf1-11e9-8fbe-e189c7d93505.png)

**Comment by samerton** [comment] 2019-08-31 20:42
Is Nameless installed in a subfolder or directly in the root (eg directly at `yoursite.com`)?

**Comment by Dinoosawruss** [comment] 2019-08-31 23:18
Hi I’m Dino the other owner of the server,

Nameless is installed in the public-html directory

**Comment by samerton** [comment] 2019-09-02 17:50
Would you be able to send me a link to your website?

**Comment by Dinoosawruss** [comment] 2019-09-02 22:06
LazuriteMC.org

**Comment by Dinoosawruss** [comment] 2019-09-03 01:29
I will add that /bans (the litebans extension) does work fine

**Comment by samerton** [comment] 2019-09-03 17:27
Ah right, so visiting `yoursite.com/index.php?route=/store` does not redirect to the store as expected?

**Comment by masonzettle** [comment] 2019-09-03 17:57
No it does not, and we want to have it so users can go to the store just by doing LazuriteMC.org/store

**Comment by samerton** [comment] 2019-09-03 18:13
Should have been fixed back in [this commit](https://github.com/NamelessMC/Nameless/commit/a27618bdd5d28f38fa53bbdb64423deb1af2cfd0) which will be included in the next release, or you can also apply the fix manually.

**Comment by masonzettle** [comment] 2019-09-03 21:03
I tried to apply the commit manually, but now my forum doesn't work at all. It just gives me HTTP ERROR 500. Any ideas?

**Comment by samerton** [comment] 2019-09-05 17:57
An error 500 suggests a PHP syntax error, which would have been caused by copying the changes incorrectly into the files, or if you replaced the whole file there might be a breaking change (eg one that requires a database change) in an earlier commit.

I can only recommend checking the changes from the commit were applied exactly, or waiting until the next update although there's no ETA on that yet I'm afraid.

**Comment by masonzettle** [comment] 2019-09-07 15:20
I have applied the commit manually, but redirects seem to only work if you're logged into the website. Otherwise, it just takes you to the 404 page. I have guests permissions allowed for all redirect pages, but that doesn't seem to work. Any ideas on why this happens?

**Comment by samerton** [comment] 2019-09-14 19:53
I'll take a look and let you know if I find anything

**Comment by masonzettle** [comment] 2019-09-21 17:30
Were you able to find anything since your last comment?

**Comment by samerton** [comment] 2019-09-29 15:34
I'm afraid I can't reproduce the issue at all, everything seems to be working as intended on my end.

**Comment by Dinoosawruss** [comment] 2019-09-29 17:50
We are definitely still having this issue

As you will see http://lazuritemc.org/vote1 requires you to log in but the page permissions allow everyone
![image](https://user-images.githubusercontent.com/22278485/65836776-ff4cee80-e2e9-11e9-95c5-f74f6c2779c1.png)

**Comment by samerton** [comment] 2020-01-04 15:20
Still not able to reproduce the issue for guests.
Hopefully when pre-release 7 is out (shouldn't be too far away) any related fixes should be included.

**Comment by samerton** [comment] 2020-01-04 15:21
Closing in favour of #1584

**Closed by samerton** 2020-01-04 15:21 UTC
Labels: bug, investigating, v2
