### ISSUE TITLE
Latest Posts widget bug.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1317] opened 2018-11-20 21:18 UTC
![untitled](https://user-images.githubusercontent.com/12484505/48803356-5ffaba80-ed1a-11e8-97a3-cd18faf65e13.png)

I notice that this problem only occurs when I'm connected.

FORUM: http://prntscr.com/lkvhpo
as guest: http://prntscr.com/lkvhv0

**Comment by samerton** [comment] 2018-11-21 13:10
I can't reproduce any issues on my side.

Has one of the duplicate topics been deleted, or are they both exactly the same topic? You can check the topic ID is the same in the topic URL.

**Comment by BaxAndrei-SEC-ACC** [comment] 2018-11-21 17:14
Same. I only have one topic at this time, maybe this is the problem

**Comment by baxandrei** [comment] 2018-11-21 19:33
http://prntscr.com/llajvi

**Comment by baxandrei** [comment] 2018-11-22 10:07
I think the problem is somewhere here: https://github.com/NamelessMC/Nameless/blob/v2/modules/Forum/widgets/LatestPostsWidget.php#L65-L70 

I suppose the count does not work well.

**Comment by baxandrei** [comment] 2018-11-26 19:47
SS:
- http://prntscr.com/lnalo2
- http://prntscr.com/lnal79

website:
1. https://www.hartexcraft.tk/forum/
2. https://www.forum.baxandrei.ro/forum/

Note:
I notice that on site #2, when I'm connected, the first topic appears twice.

**Comment by samerton** [comment] 2019-01-16 21:01
Unfortunately I've still not seen this issue since, and I still have no idea what happened here.

**Comment by baxandrei** [comment] 2019-01-16 22:17
How I can help you to find the issue?

**Comment by samerton** [comment] 2019-04-06 15:39
Fixed in https://github.com/NamelessMC/Nameless/commit/7579ef4a5de8cf348c0a249e1c7dfc307f1d47bc

**Closed by samerton** 2019-04-06 15:39 UTC
Labels: bug, investigating, v2

**Comment by baxandrei** [comment] 2019-04-07 09:14
Thanx
