### ISSUE TITLE
Custom Pages broken?

### ISSUE THREAD

**Issue by Samistine** [NamelessMC/Nameless#175] opened 2016-04-19 02:57 UTC
Is custom pages broken on newest release? I am getting 403 Forbidden.

**Comment by WASasquatch** [comment] 2016-04-19 03:13
Our your files chowned to apaches users acc and chmodded for that
directory?

**Comment by Samistine** [comment] 2016-04-19 03:29
http://paste.fedoraproject.org/357201/46103620/

**Comment by WASasquatch** [comment] 2016-04-19 03:31
Cache is chowned by root and not accessable by web server.

**Comment by samerton** [comment] 2016-04-19 11:17
Looking at the permissions, they seem to be okay so this could potentially be an nginx related issue.
Can you enable error reporting (AdminCP -> Misc) and see if anything appears on the page beside a 403 error, and if not, can you check your server error logs?

**Comment by samerton** [comment] 2016-05-23 20:58
I'm going to close this issue as I can't reproduce any issues and I believe it could be down to a server configuration issue somewhere.
If it's found out to be a compatibility issue with nginx, feel free to reopen.

**Closed by samerton** 2016-05-23 20:58 UTC
