### ISSUE TITLE
Broken links when special chars are put in the title

### ISSUE THREAD

**Issue by SignorPollito** [NamelessMC/Nameless#2725] opened 2022-04-30 14:57 UTC
### Describe the issue

When you create a new discussion in the forum and you put a special character like "/" in the title, the link breaks and it gives "404 page not found".

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Go into a forum
2. Create a discussion with a special character in the title, like "/"
3. Open the discussion
4. It will eventually give you "404 Page not found" error

### Expected Behaviour

The discussion should be opened without problem

### Screenshots

This is an example of discussion that contains a broken title:
https://forum.roosterhall.net/forum/topic/117-comando-%2fsintomi-<nick>-allo-staff-della-casa-di-cura/#post-163

The "%2" is the problem, in fact it gets fixed if I remove it from the link:
https://forum.roosterhall.net/forum/topic/117-comandosintomi-%3Cnick%3E-allo-staff-della-casa-di-cura/

**Comment by PadowYT2** [comment] 2022-04-30 15:00
Duplicate of #2461

**Comment by partydragen** [comment] 2022-04-30 15:12
Yea this bug is already solved

**Closed by partydragen** 2022-04-30 15:12 UTC
Labels: bug
