### ISSUE TITLE
List of pre V2 Bugs

### ISSUE THREAD

**Issue by Aviorleking** [NamelessMC/Nameless#623] opened 2017-04-27 20:17 UTC
**First good luck ^^**

_I will also update it as the update comes_

1. AuthMe integration showing 500 error

> jquery.min.js:3 POST https://mc.delta-wings.net/admin/minecraft/?view=authme 500 (Internal Server Error)

How to reproduce it :

Go to authme integration

open the console and  check  preserve

check to add the authme integration and you have the error

2. Minecraft admin showing errors

> Uncaught TypeError: Cannot set property 'onchange' of null at ?view=account_verification:169

> Uncaught TypeError: Cannot set property 'onchange' of null at ?view=query_errors:169

> Uncaught TypeError: Cannot set property 'onchange' of null at ?view=banners:169

_Waiting for integration_

3. While trying to add a server it don't show any Add button

![image](https://cloud.githubusercontent.com/assets/15822031/25502456/e49f95ea-2b96-11e7-8114-e8b7f7cb0a59.png)

_Wainting for integration_

4. While on AdminCP with a width of 999 and below the icon is not showing up correctly

![image](https://cloud.githubusercontent.com/assets/15822031/25507267/39a98f14-2bab-11e7-8a94-5b46a321e1f3.png)

**CORRECTED !**

5. the bottom mail  button lead to a unexistant page https://mc.delta-wings.net/contact

_Waiting for integration_

6. We need a better customization on the default theme of the "there is 0 players online" _Waiting for finished integration_

**Comment by samerton** [comment] 2017-04-29 16:29
Thanks for the list, here's my initial response:

1) I can't reproduce the issue on my test sites
2) These errors will persist until the account verification, query errors and server banner pages are complete
3) Server integration is not yet complete, hence the submit button not showing
4) Interesting, must have been caused by a recent Bootstrap update. I'll try to fix it shortly.
5) The contact page has not yet been added
6) Once Minecraft integration is complete, the 0 players online message will function normally, and will be fully customisable.

**Comment by samerton** [comment] 2017-04-29 16:53
4) has been temp-fixed by 95c41176efde0d36a085a5efb97ef441ecfc18eb, should be fully fixed in the next Bootstrap v4 alpha release.

**Comment by Aviorleking** [comment] 2017-04-30 08:28
Thanks for answer I will edit with the corrections

**Comment by samerton** [comment] 2017-08-08 14:08
Just some updates:

2. Should now be fixed
3. Complete
5. Added
6. Also added

v2 pre-release 2 should have resolved these issues :)

**Closed by samerton** 2017-08-08 14:08 UTC
