### ISSUE TITLE
Nameless's Discord embed transforms "Š" symbol into "&scaron;"

### ISSUE THREAD

**Issue by dexasz** [NamelessMC/Nameless#1906] opened 2020-11-07 04:07 UTC
![embed](https://user-images.githubusercontent.com/37642364/98431591-7d6bef00-20bf-11eb-9a8d-9fb01a0ae6db.png)

**Comment by Derkades** [comment] 2020-11-07 08:43
Possibly duplicate of #1628

**Comment by Aberdeener** [comment] 2020-11-12 05:57
Closing this issue as it has been fixed in the commit Derkades linked. Feel free to reopen if your issue is not resolved still.

**Closed by Aberdeener** 2020-11-12 05:57 UTC
