### ISSUE TITLE
null

### ISSUE THREAD

**Issue by Toxic-Waste** [NamelessMC/Nameless#44] opened 2015-12-06 14:49 UTC
Every page in the left corner has the word null on it
![null](https://cloud.githubusercontent.com/assets/1909777/11613876/42521870-9bf6-11e5-9134-6b515d903c30.png)

**Comment by Adobes** [comment] 2015-12-06 15:26
Do you have error-reporting enabled?

**Comment by samerton** [comment] 2015-12-06 15:40
Try disabling the Google Analytics core module.

**Comment by Toxic-Waste** [comment] 2015-12-06 21:33
that worked ty on that mod page it shows double of everything like to registrations 2 social media and everything else

**Comment by samerton** [comment] 2015-12-06 21:34
Strange, I'll have a look into it now.

**Comment by Toxic-Waste** [comment] 2015-12-06 21:53
![double array](https://cloud.githubusercontent.com/assets/1909777/11615859/7d90ab96-9c31-11e5-88f2-25d91b7a4e4b.png)

**Comment by dwilson390** [comment] 2015-12-10 19:26
Can confirm.  The issue is caused by the software scanning and adding duplicate entries to the database table 'nl1_core_modules', issue also affects themes.  This can be fixed by deleting them from your MySQL database however.

**Comment by SystemUpdate** [comment] 2015-12-13 13:30
What about adding a page to the admin area which scans for duplicate entries?

**Comment by dwilson390** [comment] 2015-12-13 13:38
Would it not be better to simply add the feature to the scanner, simply verifying the path to the theme/module doesn't already exist in the database, before inserting the record?  

Alternatively, a button (for example "Check for Duplicates") is another option.

**Comment by SystemUpdate** [comment] 2015-12-13 13:58
Or do both

**Comment by dwilson390** [comment] 2015-12-13 14:08
Seems like the best option.  Though if the scanner could be fully relied upon to not produce duplicates, the button wouldn't be necessary.

**Comment by SystemUpdate** [comment] 2015-12-13 14:15
Many users still have dupe entries from other issues as well.

**Comment by samerton** [comment] 2015-12-13 14:37
It seems the code to insert the core modules and the themes is being run twice, this could be down to the user clicking "submit" in the particular installer stage multiple times.

I'll add a check to prevent the values from being inputted multiple times.

**Closed** 2015-12-13 14:37 UTC
