### ISSUE TITLE
Post api registration email does not ask to set password

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#2074] opened 2021-01-29 21:16 UTC
If you have your registration setup as to have to run `/register {email}` in-game it sends a verification email.
Well, when you click that link it just validates the account. It does not ask to apply a password or accept terms and privacy policy.

And on the subject of verification, it would be nice that if accounts that do not get validated after x time the account is wiped from the website and the command would need to be executed again to start the signup process again. This would also be nice for password resets too if the links go unused after x time, invalidate the link.

**Comment by Derkades** [comment] 2021-01-29 22:08
> it would be nice that if accounts that do not get validated after x time the account is wiped from the website

See #1519 

> or accept terms and privacy policy.

See #1769 (created by you!)

> It does not ask to apply a password

That does sound like a bug. Does this mean users have to use "forgot password" to set a password to be able to log in?

**Comment by StormyIceLeopard** [comment] 2021-01-29 22:21
> That does sound like a bug. Does this mean users have to use "forgot password" to set a password to be able to log in?

Correct! And on that page it would be nice to have it say "By clicking Complete Registration you agree to the Terms and Conditions and Privacy Policy"

**Comment by samerton** [comment] 2021-01-30 12:23
What is the URL in the email? It should be `yoursite.com/complete_signup?c=....`

**Comment by StormyIceLeopard** [comment] 2021-01-30 15:59
> What is the URL in the email? It should be `yoursite.com/complete_signup?c=....`

`yoursite.com/validate/?c=....`

**Comment by Derkades** [comment] 2021-01-30 22:54
What does the plugin say in chat after using the /register command?

**Comment by StormyIceLeopard** [comment] 2021-01-31 00:19
> What does the plugin say in chat after using the /register command?


![](https://media.discordapp.net/attachments/287345673207021568/805230445931397140/Capture.PNG)

**Comment by Derkades** [comment] 2022-04-06 21:18
I can confirm the `/complete_signup/?c=fd21432f4b8d5f89cb88b26c46a641b28b752a621ec4efdc8b580b1100c232e6` link does not prompt for a password. I am using the user integration branch.

**Comment by Aberdeener** [comment] 2022-05-15 21:25
Closing since Party confirmed this is working in the expected behaviour

**Closed by Aberdeener** 2022-05-15 21:25 UTC
Labels: bug
