### ISSUE TITLE
AuthMe integration doesn't work

### ISSUE THREAD

**Issue by faneQ123** [NamelessMC/Nameless#1637] opened 2020-04-20 12:47 UTC
Set the mysql connection and credentials properly. Changed the login and register method as Username.
When I try to register i use the username and password that i've used to create the account ingame but nothing happens , no error showned , no fail messages , not loging in.

When i try to login using the username and pass created ingame with authme , it says Wrong credentials.
Checking the mySql server no connection is made between the namelessmc server and the sql server

https://prnt.sc/s2opnb - nameless configuration
https://prnt.sc/s2oq69 - authme configuration

**Comment by samerton** [comment] 2020-04-20 18:50
Resolved in Discord, was caused by MySQL privileges

Pushed https://github.com/NamelessMC/Nameless/commit/3698d497823c5595cab4acfb30cf17c86fb325e9 to fix issues with error messages not showing in default revamp template when using the authme connector

**Closed by samerton** 2020-04-20 18:50 UTC
