### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by KryipticKing** [NamelessMC/Nameless#1016] opened 2018-05-04 21:22 UTC
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Latest
**How would you describe the issue?** Whenever I click submit to register my admin account, it goes to the convert page for about 1/2 a second and jumps to a different page.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](https://imgur.com/a/B0AwDay) 
**Do you have an idea how or where the issue occurs?** The CSS file is gone?

ALSO: I have it on a subdomain, to get to it, it is on the root folder inside a folder called 'forums.' I have even tried re-installing it and it still won't work. HOW???!!!

**Comment by samerton** [comment] 2018-05-05 13:14
Hi,

This is usually caused by Nameless being installed in a subfolder (eg yoursite.com/forum). Nameless version 1 will not work in a subfolder, it must be either directly at yoursite.com *or* you can point a subdomain to it (eg forum.yoursite.com).

**Comment by KryipticKing** [comment] 2018-05-05 14:33
Thanks for your help. However, it didn't work. I have it on a subdomain, to get to it, it is on the root folder inside a folder called 'forums.' I have even tried re-installing it and it still won't work. HOW???!!!

**Comment by samerton** [comment] 2018-05-05 14:35
Are you installing on a web host, or a VPS/dedicated server? If you're on the latter, is it Apache/nginx?

**Comment by KryipticKing** [comment] 2018-05-05 14:36
WHOA. You replied really fast!
It is on a webhost.

**Comment by samerton** [comment] 2018-05-05 14:49
Can you make sure that, in your Nameless installation folder, there is a file named `.htaccess` and that it contains [these rules](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess)? 
Note that if your web host uses cPanel, and you use cPanel's file manager, htaccess files are hidden by default and can be shown by clicking on the settings icon in the top right.

Also, was the install.php file moved at all? Its correct location is within the **pages** folder.

**Comment by KryipticKing** [comment] 2018-05-05 14:51
Yes. It does have the file and the script inside it.

**Comment by samerton** [comment] 2018-05-05 19:56
In that case I'm not sure what the problem is, would you be able to send me a link to your site?

**Comment by KryipticKing** [comment] 2018-05-05 22:44
forums.platinumrealm.net

**Comment by KryipticKing** [comment] 2018-05-06 16:03
Yes my user has been created. I did delete the other ones because I tried creating an account about 15 times. I did leave the original user there though.

**Comment by samerton** [comment] 2018-05-06 17:49
I have seen this issue before, but I really can't remember what the cause was.

Can you try editing pages/install.php in a text editor, delete all code inside, and replace it with [this new code](https://gist.githubusercontent.com/samerton/839f62ebde45c878006f65ad12b0f511/raw/4b60d56a2034c0e5c1da433668f634f56f1164aa/install.php)? Then, try creating the admin account in the installer again to see if an error appears on screen (this will result in a duplicate admin account which will have to be deleted in phpMyAdmin again).

**Comment by KryipticKing** [comment] 2018-05-07 01:44
I did get this error after I clicked submit on the MySQL database setup:
Warning: Unknown: open(/var/php_sessions/sess_70124dfde10b2137912ac6fa0159afdb, O_RDWR) failed: No such file or directory (2) in Unknown on line 0 Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/php_sessions) in Unknown on line 0.

I also got this error when I tried to create an account:
Warning: Unknown: open(/var/php_sessions/sess_70124dfde10b2137912ac6fa0159afdb, O_RDWR) failed: No such file or directory (2) in Unknown on line 0 Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/php_sessions) in Unknown on line 0

**Comment by samerton** [comment] 2018-05-07 10:12
Ah okay, so the problem is that sessions aren't being saved; if you can contact your web host and provide them with this error they will be able to help out.

**Comment by samerton** [comment] 2018-05-09 16:26
Were you able to contact your web host @KryipticKing?

**Comment by samerton** [comment] 2018-05-15 15:02
I'll mark this as closed as this is a hosting related issue; if you are still experiencing this feel free to re-open.

**Closed by samerton** 2018-05-15 15:02 UTC
