### ISSUE TITLE
Error when saving after removing all groups from a user

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2296] opened 2021-06-27 20:23 UTC
in_array(): Argument #2 ($haystack) must be of type array, null given
(File: /data/modules/Core/pages/panel/users_edit.php)

/data/modules/Core/pages/panel/users_edit.php line 245

/panel/users/edit/?id=1

**Comment by Derkades** [comment] 2021-06-27 20:56
Only happens with admin users, normal users give a "You must select a user's group" error when trying to save with no groups selected. For the admin user, the primary group is not included in the secondary group selection box while for normal users it is.

**Comment by samerton** [comment] 2021-08-24 18:57
Duplicate of #2335

**Closed by samerton** 2021-08-24 18:57 UTC
Labels: bug
