### ISSUE TITLE
Topic reply language error

### ISSUE THREAD

**Issue by MarkiThePews** [NamelessMC/Nameless#1387] opened 2019-01-30 05:21 UTC
**Describe the issue**
Using custom avatar will cause error loading language when posting replies in forum.
doesn't happen when posting topic.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable custom avatar
2. Create an account (Login)
3. Use a custom avatar
4. Post a reply in any topic
5. See error

**Expected behaviour**
Showing blank screen with error text: 
`Error loading language file at X.php in X`
~> X is the first character of your username or nickname (tested in 2 accounts with same User/Nickname start so idk which)

**Screenshots**
https://i.imgur.com/2d1BrS1.png

**NamelessMC version (from AdminCP -> Overview)**
Lastest v2 on github (except 0ce08cd, but it have no relate with posting reply I think)

**Comment by MarkiThePews** [comment] 2019-01-31 11:43
Update: not caused by avatar.

**Comment by MarkiThePews** [comment] 2019-01-31 13:38
Update: mysql truncated: (all with nl2_ prefix)
forums_reactions
logs
posts
private_messages* (3 tables)
topics* (2 tables)
users_* (nl2_users is not truncated)
user_*
~> no more error, weird enough.

**Comment by samerton** [comment] 2019-02-17 12:41
Fixed in https://github.com/NamelessMC/Nameless/commit/90edce649e80a52f880459d33f98bc6f3c1e696b

The issue was caused by alerts being broken for topic following; when at least 1 user was following the topic and a reply was created, it would fail to load some language terms causing the error.

**Closed by samerton** 2019-02-17 12:41 UTC
Labels: bug, help-wanted, investigating, v2
