### ISSUE TITLE
The requested URL /install.php was not found on this server.

### ISSUE THREAD

**Issue by Cmonster-11** [NamelessMC/Nameless#263] opened 2016-06-23 16:22 UTC
* What kind of issue is it (Question, Bug, etc.)? Missing File

* In which version of NamelessMC did it occur (1.x.x)? 1.0.9

* How would you describe the issue?  When i attempt to load up NamelessMC for the first time and install it, it attempts to redirect me to IPADDRESS/install.php, i also tried to use 1.0.10 but it did something similar, when  it attempts to direct me it gives me a 404 Not Found (Not Your 404.php), saying the page wasn't found.

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Screenshot: https://gyazo.com/cd2c871172458ffd82a2c5d4ce

* Do you have an idea how or where the issue occurs? 
When i downloading the archive (tar.gz as i am on linux web server os) the install.php file is not included.

**Comment by samerton** [comment] 2016-06-23 16:42
[This](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) should help you out.

**Comment by Cmonster-11** [comment] 2016-06-23 17:03
Just tried all of that, it does not appear to work, also if it helps, i am running Debian 8.

**Comment by samerton** [comment] 2016-06-23 17:06
Can you check a file named ".htaccess" exists in your web root (usually /var/www or /var/www/html), and it contains [these rules](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess)?

The pages directory is the correct location for the install file, as the htaccess file will be able to load it normally within there.

**Comment by Cmonster-11** [comment] 2016-06-23 17:07
despite it not showing from "ls" i have nano'd it in there just for confirmation.

**Comment by Cmonster-11** [comment] 2016-06-23 17:32
Update: I got it working, after alot of editing of the apache2.conf.
Stay Tuned For Next Episode!

**Comment by samerton** [comment] 2016-06-23 17:33
Glad it's working! :)

**Comment by Cmonster-11** [comment] 2016-06-23 18:07
Now i am receiving permission based errors, regarding core/config.php

What is the default chmod i should be using on the /var/www/html/ directory?
and the chown i should be using,

**Comment by samerton** [comment] 2016-06-23 18:10
Can you try:

chown -R www-data:www-data /var/www/html

**Comment by Cmonster-11** [comment] 2016-06-23 18:12
I am about to re-install, because for some apparent reason the css wasn't working, what version would you recommend
?

**Comment by Cmonster-11** [comment] 2016-06-23 18:26
Screenshot of current error: https://gyazo.com/09cb86c4a6a1d84a60a14e2f090fe845

**Comment by samerton** [comment] 2016-06-23 18:29
Interesting, suggests there's a problem in your Apache configuration. Not sure what it could be, but [this](http://askubuntu.com/questions/413887/403-forbidden-after-changing-documentroot-directory-apache-2-4-6) might be able to shed some light.

**Comment by Cmonster-11** [comment] 2016-06-23 18:30
This is also the index.php page i am receiving: https://gyazo.com/73da5c86e0b437d02249162c3ac4129d

Whereas before it was showing with all the css working fine, i am assuming this is related to the permissions?

**Comment by Cmonster-11** [comment] 2016-06-23 18:43
Okay, now CSS is working.

**Comment by Cmonster-11** [comment] 2016-06-23 18:43
Now i am getting this error: https://gyazo.com/8e4509fd12644d1d327e99baff3a3721

**Comment by Cmonster-11** [comment] 2016-06-23 19:05
bumpity :P

**Comment by samerton** [comment] 2016-06-23 19:24
Can you double check the .htaccess exists, as in a previous reply? Sometimes it can be lost whilst reuploading/moving files.

**Comment by Cmonster-11** [comment] 2016-06-23 19:26
Yeah it does.

**Comment by Cmonster-11** [comment] 2016-06-23 19:27
For some reason, those files do not show in "ls" but yeah it does, i autocompleted it, nano'd it, its all there.

**Comment by Cmonster-11** [comment] 2016-06-23 19:31
I am now using the latest version btw.

**Comment by samerton** [comment] 2016-06-23 21:02
The only fix for this is the steps in [this post](http://askubuntu.com/a/48363) which I believe you followed earlier, I can only ask if you followed _all_ steps in that guide (including the commands at the top of the post), and did you restart Apache afterwards?

**Comment by Cmonster-11** [comment] 2016-06-24 02:57
https://gyazo.com/c0248530b608e16fed394e302b57e130 :(

Did all of that, multiple times, including re-installing apache.

**Comment by Cmonster-11** [comment] 2016-06-24 03:20
The main issue, is with all of these tutorials, they are all for Ubuntu, and refer to a non-existant file "default" located in sites-available.

The only files i have in that directory is 000-default.conf and ssl-default.conf or something similar.

and the 000-default.conf doesn't have any of those options, only the apache2.conf in the /etc/apache2 directory has them.

**Comment by Cmonster-11** [comment] 2016-06-24 03:27
I am still getting a 403 Forbidden error.

**Comment by Cmonster-11** [comment] 2016-06-24 11:10
Should i attempt to downgrade to 1.0.9?

**Comment by samerton** [comment] 2016-06-24 11:17
This will be a server configuration issue as opposed to a Nameless issue, can you try removing the top line of the .htaccess file (currently `Options +FollowSymLinks`)

**Comment by Cmonster-11** [comment] 2016-06-24 11:23
No change.

**Comment by samerton** [comment] 2016-06-24 11:25
Can you try the command **ls -l /var/www/html** to view the owners/permissions of the web files?

**Comment by Cmonster-11** [comment] 2016-06-24 11:29
https://gyazo.com/811cb74e60b4b7b110ed7ca32ede173e

**Comment by samerton** [comment] 2016-06-24 11:31
Everything seems to be in order, can you paste the

`<Directory /var/www/html>`

block from within your /etc/apache2/apache2.conf file?

**Comment by Cmonster-11** [comment] 2016-06-24 11:34
<Directory /var/www/html/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride FileInfo
        Order allow,deny
        allow from all
</Directory>

**Comment by samerton** [comment] 2016-06-24 11:40
Try AllowOverride from FileInfo to All, and restart Apache.

**Comment by Cmonster-11** [comment] 2016-06-24 11:42
Sometimes i hate OVH rn, i can't even connect to my bloody VPS. sigh
1 moment.

**Comment by Cmonster-11** [comment] 2016-06-24 11:43
Alright, its back, and still not working :(

**Comment by samerton** [comment] 2016-06-24 11:47
Unfortunately I'm out of ideas, I've not seen the 403 forbidden error before so I don't know what the cause could be. It might be worth looking around for people who have also experienced the 403 forbidden error on Apache.
If you'd like me to take a look, feel free to send me a PM on Spigot,

**Comment by Cmonster-11** [comment] 2016-06-24 11:55
I am going to try resetting my vps, just gotta find somewhere to temporarily copy my files (Local is way too slow :P)

**Comment by jesseke55** [comment] 2016-06-24 13:50
The error 403 may occur by the wrong locations in the apache configuration

**Comment by Cmonster-11** [comment] 2016-06-24 14:21
Explain?

**Comment by Cmonster-11** [comment] 2016-06-24 14:33
@samerton https://gyazo.com/16cea0d095f3890c11f8184608cd29fa
If that helps at all, in regards to the permissions.

**Comment by Cmonster-11** [comment] 2016-06-24 14:43
I just did a full re-install of my Apache, lets go for round 2 :p

**Comment by Cmonster-11** [comment] 2016-06-24 15:10
@samerton @jesseke55 Issue appears to be fixed now, re-installed Apache, edited minimal things this time, following the FAQ's and chown etc, have made it through the installation proccess

**Comment by samerton** [comment] 2016-06-24 15:22
Glad your issue is resolved!

**Closed by samerton** 2016-06-24 15:22 UTC
