### ISSUE TITLE
[Bug] I can not create banner and in status, the list of users does not load

### ISSUE THREAD

**Issue by thecloudff7** [NamelessMC/Nameless#1408] opened 2019-02-23 23:04 UTC
* What kind of issue is it (Question, Bug, etc.)?
Bug

* In which version of NamelessMC did it occur (1.x.x)?
2.0.0-pr5

* How would you describe the issue?
I can not create banner and in status, the list of users does not load. Using the internal query, but I also tried the external query and it does not work. Just put me the number of users in the index.

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
https://i.imgur.com/lB5oIN2.png -- Loading status
https://i.imgur.com/6L430wb.png -- banner

* Do you have an idea how or where the issue occurs?
no

* What Modules are you using ?
Core, Forum and Default

* What theme are you using ?
Default

**Comment by samerton** [comment] 2019-02-24 15:05
Firstly, can you make sure that the "External Query" option is **disabled** in the StaffCP -> Integrations -> Minecraft -> Servers tab.

Then, wait a few minutes, view the Status page again, and check the StaffCP -> Integrations -> Minecraft -> Query Errors tab to see if anything appears.

**Comment by thecloudff7** [comment] 2019-02-24 15:27
External Query is disabled.
In  Query Errors: https://i.imgur.com/RowOaHi.png


And with the banners that I can do?

**Comment by samerton** [comment] 2019-02-24 15:29
The error means that your web host is either:
- preventing the use of PHP sockets
- blocking port 25565

You can contact your web host to see if they can enable these for you.

The banners issue is also caused by this problem.

**Comment by thecloudff7** [comment] 2019-02-24 15:57
Sorry, but I do not understand. The port 25565 is open and I do not have a web hosting but a vps.

I have to close the php sockets? How do I do that?
I do it in the vps of the server or the vps of the web?

**Comment by samerton** [comment] 2019-02-24 16:11
I've had a look on my own site and it can't connect to the server either, suggesting the problem is with the domain `mc.firemods.net`.

Is this the domain you use to connect to the server with ingame?

**Comment by thecloudff7** [comment] 2019-02-24 16:14
yes. The ip is 158.69.123.59:25565

**Comment by samerton** [comment] 2019-02-24 16:15
I'm getting the same error ingame (connection refused) when joining with `mc.firemods.net`, so the problem is with the domain.

Make sure you have an A record set up in your DNS settings within the domain registrar pointing the IP to the domain.

**Comment by thecloudff7** [comment] 2019-02-24 22:12
Yep, firemods.net pointing to 158.69.123.59

**Comment by samerton** [comment] 2019-02-27 18:16
The domain has now been updated and it is correctly pointing to the Minecraft server for me now.

Does the website query work for you now?

**Comment by thecloudff7** [comment] 2019-02-28 19:43
No, I can't ;( How have you verified that it works?

**Comment by samerton** [comment] 2019-02-28 20:10
I added the server in my StaffCP and it's successfully querying using the domain.

Is the error message in the StaffCP -> Integrations -> Minecraft -> Query Errors tab still the same?

**Comment by thecloudff7** [comment] 2019-02-28 20:38
It worked fine today.

You use mc.firemods.net or IP address?

**Comment by samerton** [comment] 2019-02-28 21:05
I used mc.firemods.net for the server in the StaffCP.

**Comment by thecloudff7** [comment] 2019-02-28 21:10
This is my config: https://i.imgur.com/ewdYoag.png
But Status page dosn't work: https://i.imgur.com/rlyXE8B.png

**Comment by samerton** [comment] 2019-02-28 21:48
I'm afraid I don't know what the problem is, but it appears to be server configuration related as the query works fine for me.

Can you double check that the ports are open on the web server (eg port 25565)?

**Comment by samerton** [comment] 2019-03-09 18:32
Any updates on this @thecloudff7?

**Comment by samerton** [comment] 2019-03-14 17:33
I'll mark this issue as closed as it's either caused by:
- the domain DNS
- the web host blocking the query
- the game host blocking the query

**Closed by samerton** 2019-03-14 17:33 UTC
Labels: question, v2
