### ISSUE TITLE
Undefined Offset Error After Deleting Forum Posts

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#453] opened 2016-10-18 08:58 UTC
NamelessMC Version 1.0.13
Running PHP 5.5.9-1ubuntu4.14

After deleting the 3 most recent posts in my forums, this error appeared: https://i.gyazo.com/3fd3e35053e97c52555338f360d8dd1c.png

Forums page: http://www.pandacraft.org/forum

**Comment by samerton** [comment] 2016-10-18 09:06
Thanks for the report, I think I can see the cause of the issue. I'll take a look now.

**Comment by samerton** [comment] 2016-10-18 09:15
Should be fixed in dfa48ed766b89a8aa057d5f40fa960be08e2badd, although unfortunately it won't fix issues with already deleted topics, only topics which will be deleted in the future. The error message can be hidden by disabling error reporting in the AdminCP -> Misc tab for now though.

To apply the changes now, you can replace **pages/forum/delete_post.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/pages/forum/delete_post.php).

**Closed** 2016-10-18 09:16 UTC
Labels: bug
