### ISSUE TITLE
Language question v2

### ISSUE THREAD

**Issue by haer0248** [NamelessMC/Nameless#946] opened 2018-01-10 12:31 UTC
Can I help translate Traditional Chinese? 
NamelessMC version 2.0.0-pr3

**Comment by haer0248** [comment] 2018-01-10 12:33
Sorry, I didn't how to set label.

**Comment by Derkades** [comment] 2018-01-10 14:55
Labels can only be set by administrators

Fork the project (v2 branch), go to /custom/languages, copy EnglishUK and call it "Chinese", edit the files then submit a pull request. Thanks for contributing, if you have any further questions let me know.

**Comment by samerton** [comment] 2018-01-10 23:07
Yes, the forum language file can be found in the **modules/Forum/language** folder :)

**Comment by haer0248** [comment] 2018-01-12 13:29
Maybe It is Bug...
when I enable the **maintenance** mode
then I logout can no longer login...

**Comment by samerton** [comment] 2018-01-12 13:30
@haer0248 You can go straight to **yoursite.com/login** and log back into your account there

**Comment by haer0248** [comment] 2018-01-12 13:36
can't! 404 Error..
So I reinstall the site ...

**Comment by samerton** [comment] 2018-01-12 13:37
@haer0248 If you have friendly URLs disabled, the URL will be **yoursite.com/index.php?route=/login**

**Comment by haer0248** [comment] 2018-01-12 13:38
Yes, URL is 127.0.0.1/index.php?route=/login ...
But 404...

**Comment by samerton** [comment] 2018-01-12 13:39
@haer0248 Can you try both **index.php?route=/login** and **index.php?route=/login/** (with the / at the end)

**Comment by haer0248** [comment] 2018-01-12 13:42
I tried.
Are the same.

**Comment by samerton** [comment] 2018-01-12 13:43
@haer0248 That's very strange, unfortunately I don't know what the problem is.

**Comment by haer0248** [comment] 2018-01-12 13:44
OMG..
I am reinstalling the site.
I will try again.

**Comment by haer0248** [comment] 2018-01-12 14:05
OMG!! Maybe is my problem!!
I can use 127.0.0.1/login to login in maintenance mode!
Sorry!!

**Comment by haer0248** [comment] 2018-01-12 14:57
Hello, Chinese almost done!!
https://github.com/haer0248/NamelessMC-Chinese
Remaining "moderator.php"

**Comment by haer0248** [comment] 2018-01-12 15:11
ok! all done.

**Comment by samerton** [comment] 2018-01-12 15:27
@haer0248 Thanks a lot! :)

Would you like to create a resource over in our [resources section](https://namelessmc.com/resources/), or would you like to include the translation within the NamelessMC download? 
For the latter, you can submit a pull request to this repository, or I can include it for you if you wish.

**Comment by haer0248** [comment] 2018-01-12 16:00
OK... I'm glad to, but my English is very poor. 
Talk with you maybe to use Google translation to communicate

**Comment by haer0248** [comment] 2018-01-12 16:04
Maybe I can create resources and translate

**Comment by haer0248** [comment] 2018-01-13 10:07
I upload the **"forum.php** Chinese language
https://github.com/haer0248/NamelessMC-Chinese

**Comment by haer0248** [comment] 2018-01-13 10:29
Did you know how to fix this problem?

Notice: Undefined offset: 0 in A:\xampp\htdocs\core\init.php on line 116
Notice: Trying to get property of non-object in A:\xampp\htdocs\core\init.php on line 116

Xampp Apache

**Comment by samerton** [comment] 2018-01-13 12:40
Thanks for the forum translation :)

Would I have your permission to add the Chinese translation straight into Nameless?

As for the error, I don't think it will cause any issues and you are safe to ignore it. You can disable debugging in the AdminCP -> Core -> Debugging and Maintenance tab to hide these messages.

**Comment by haer0248** [comment] 2018-01-13 13:07
Yes, you can add it!

**Comment by haer0248** [comment] 2018-01-13 13:31
I fix it! Thanks <3

**Comment by samerton** [comment] 2018-01-13 13:32
One thing I noticed is that the translation is licensed under GPL-3.0, unfortunately this wouldn't be compatible with Nameless' MIT license.

**Comment by haer0248** [comment] 2018-01-13 13:33
Oh?

**Comment by samerton** [comment] 2018-01-13 13:35
This just means that, due to the GPL license, I can't include it in the NamelessMC download I'm afraid.

You would be able to list it as a resource in our [resources section](https://namelessmc.com/resources), though.

**Comment by haer0248** [comment] 2018-01-13 13:36
So should I set it to?

**Comment by samerton** [comment] 2018-01-13 13:37
If you could update the license to MIT, I can include the files :)

**Comment by haer0248** [comment] 2018-01-13 13:42
OK~ set done!
https://github.com/haer0248/NamelessMC-v2-Traditional-Chinese

**Comment by haer0248** [comment] 2018-01-13 14:12
@samerton OMG ... The forum topic when I open the "Display topics as news on front page?" the topic will go to 404...

**Comment by samerton** [comment] 2018-01-13 14:13
@haer0248 Can you make sure your NamelessMC v2 code is up to date? The latest code is [here](https://github.com/NamelessMC/Nameless/archive/v2.zip).

**Comment by haer0248** [comment] 2018-01-13 14:18
Yes... I just downloaded

**Comment by haer0248** [comment] 2018-01-13 14:19
And the label .... 
![default](https://user-images.githubusercontent.com/25150003/34906815-cf9ec04e-f8af-11e7-9749-bc65a3fc483b.png)

**Comment by haer0248** [comment] 2018-01-13 14:28
And ... Discord server can't show

**Comment by samerton** [comment] 2018-01-13 14:59
Thanks again for the translation, I have added it in 2e665a35d7253b59e3a0329b7309ea59bcc26cd7.
There are a couple of extra terms I have added (which have been added in recent commits), however these are still in English.

As for the 404 issue, can I ask what the URL is when you click on the forum topic on the homepage?

I can only imagine the label HTML that isn't showing its colour is incorrect, the correct HTML depends on your Nameless v2 version. The HTML if you're using the latest code can be found [here](https://getbootstrap.com/docs/4.0/components/badge/#contextual-variations), and if you're using an earlier pre-release I believe `badge` needs replacing with `tag`.

To get the Discord server to show, make sure you have enabled the widget in your Discord server settings -> Widget tab (right at the top).

**Comment by haer0248** [comment] 2018-01-13 15:04
404 >> https://amsserver.xyz/forum/view/8-%e4%bc%ba%e6%9c%8d%e5%99%a8%e5%85%ac%e5%91%8a/
![default](https://user-images.githubusercontent.com/25150003/34907211-0b11907e-f8b6-11e7-8c5a-5dddc2fc7351.png)
the topic is alreay exist.

I know that site, but I have to establish the corresponding label, there is a display tag, but behind a more radiobutton

**Comment by haer0248** [comment] 2018-01-13 15:09
Thanks! discord server is show now!!!

**Comment by haer0248** [comment] 2018-01-13 15:11
The discord server width .... (forum)
![default](https://user-images.githubusercontent.com/25150003/34907279-19bfd9ea-f8b7-11e7-89a6-989ac5285ff1.png)

**Comment by samerton** [comment] 2018-01-13 15:15
The 404 issue should have been fixed since the last pre-release.

As for the label issue, the labels in pr3 should actually be `badge` instead of `tag`, that's my mistake (as per the [docs](https://v4-alpha.getbootstrap.com/components/badge/#contextual-variations)). If it's still not working, you can get the label class by right clicking on it -> Inspect Element.

Finally, I can fix the Discord widget width in a future update.

**Comment by samerton** [comment] 2018-01-13 15:17
Actually, the Discord widget width was fixed in this commit: 52644fa2db65629473db4223d6bae2f9adbd7cb4

**Comment by haer0248** [comment] 2018-01-13 15:28
okay, I will check it!

BUG found....
When guest login, the website url will be lead to "website.com/favicon.ico"
It is bug or my problem?

**Comment by samerton** [comment] 2018-01-13 15:29
It's something that will be fixed for the next pre-release.

For now, you can upload a favicon to your site (make sure it's named favicon.ico, there are online image converters you can use).

**Comment by haer0248** [comment] 2018-01-14 05:09
okay.

![image](https://user-images.githubusercontent.com/25150003/34913020-f2e9b3fc-f92b-11e7-9ab6-781746c852ef.png)
I can't Query my server, please help!
The original machine can, but not to the server over there.

**Comment by samerton** [comment] 2018-01-14 12:17
@haer0248 Can you check the AdminCP -> Minecraft -> Query Errors tab, to see if anything's in there?

You can also try enabling the "Use external query?" option in the AdminCP -> Minecraft -> Minecraft Servers tab, to see if that works.

**Comment by haer0248** [comment] 2018-01-15 07:55
Yes, but not any error.
If use  external query is same as normal query.

**Comment by haer0248** [comment] 2018-01-15 08:02
I translated some not yet translated, please check it out.

**Comment by haer0248** [comment] 2018-01-15 13:53
@samerton Can add **google analytics** and **google adsense**?

**Comment by samerton** [comment] 2018-01-15 15:53
The query not working must be to do with the web host, as there are no issues with the query library itself (it's [this](https://github.com/xPaw/PHP-Minecraft-Query) library).

As for Google Analytics, there is integration in version 1 of Nameless, however not version 2 yet, it's coming soon. For now you can add the Google Analytics script into core/templates/header.php.
I can have a look into Adsense in the future.

**Comment by haer0248** [comment] 2018-01-15 22:07
Ok! I will add it.

**Comment by haer0248** [comment] 2018-01-17 13:46
@samerton Hello! My website contact email can't to use.
Error message: SMTP Error: Could not connect to SMTP host. 
My firewall is open 25 465 and 587. host is smtp.gamil.com
please help !!

**Comment by samerton** [comment] 2018-01-17 13:49
@haer0248 Can you edit **core/classes/Email.php** in a text editor, delete all code inside, and replace it with [this new code](https://gist.githubusercontent.com/samerton/a26df55561f9735eb2f69af6868f57fb/raw/e43a56de9b33a0d62c09ab4e1d77055fc832edb0/Email.php)?

Then, if you try sending another test email, hopefully you'll get a full error message.

**Comment by haer0248** [comment] 2018-01-17 22:24
Thanks, I will try it!

**Comment by haer0248** [comment] 2018-01-18 09:18
Bug found(maybe)
In RWD mode, header can't scroll.
If scroll, the page will move together.
Website: https://amsserver.xyz/ (Chinese, please excuse)

**Comment by haer0248** [comment] 2018-01-18 11:28
Can't send Email. :(

**Comment by haer0248** [comment] 2018-01-18 11:30
And the Query still can't get server information.
Can you change to the API provided by [this website](https://api.mcsrvstat.us/)?

**Comment by samerton** [comment] 2018-01-18 12:14
What do you mean by RWD mode? I've had a look at the site and everything seems normal.

As for emails not sending, did you update the code for **core/classes/Email.php** from my previous reply? If so, can you then check the AdminCP -> Core -> Email -> Errors tab to see if there are more detailed errors in there now.

I can have a look into adding support for another API in the future, but it won't happen any time soon I'm afraid. [This API](https://docs.gameapis.net/docs/mc/query) is used at the moment and I've not experienced any issues with it so far, can you check your server with that?
As a side-note, the internal query is provided by [this library](https://github.com/xPaw/PHP-Minecraft-Query).

**Comment by haer0248** [comment] 2018-01-18 12:20
IP: amsserver.xyz
RWD mean "Responsive Web Design"

**Comment by samerton** [comment] 2018-01-18 12:22
Ah okay, I did have a look in mobile view, and everything seems to be working as intended. If you want to, you can modify the template in the styles/templates/*template*/ folder, to make any layout changes in there.

**Comment by haer0248** [comment] 2018-01-19 08:19
I found the "PHPmailer" core.
Maybe is this problem so I can't send mail?
in **core\includes\phpmailer**

**Comment by samerton** [comment] 2018-01-19 11:44
What do you mean by that? 
PHPMailer is required if you are using SMTP to send emails through Nameless, as long as you have filled out your SMTP details in the AdminCP -> Core -> Emails tab.

**Comment by samerton** [comment] 2018-01-25 12:24
Were you able to fix the problem @haer0248?

**Comment by haer0248** [comment] 2018-01-25 12:39
Fix Email?
I can't ;(

**Comment by haer0248** [comment] 2018-02-01 05:18
@samerton 
Can you give me the "authme" SHA256 PHP encryption method?
I want to be my own website login page.
 https://faq.amsserver.xyz/player

**Comment by samerton** [comment] 2018-02-01 09:05
Unfortunately I can't help with the email problem, the updated code for Email.php I sent you should show a bigger error message instead of just "SMTP Error: Could not connect to SMTP host.". I can only recommend checking out [this link](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host).

As for the SHA256 auth method, you can find the corresponding code for that [here](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/User.php#L273-L282).

**Comment by haer0248** [comment] 2018-02-15 02:31
Thanks for helping my password problem.
Can you tell me how to make the "TFA" in PHP?

**Comment by samerton** [comment] 2018-02-15 09:10
Nameless includes [this library](https://github.com/RobThree/TwoFactorAuth) for TFA, an example of verifying a code entered by the user is [here](https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/pages/login.php#L71-L77).

**Comment by haer0248** [comment] 2018-02-15 09:26
OMG!! Thanks you very much!

**Comment by samerton** [comment] 2018-02-15 14:09
No problem, I'll go ahead and mark this issue as closed, it's been open for a while :P

**Closed by samerton** 2018-02-15 14:09 UTC
Labels: question, v2

**Comment by haer0248** [comment] 2018-02-15 14:10
okay, thanks!
