### ISSUE TITLE
Problem with my server popping up as online on the play tab

### ISSUE THREAD

**Issue by SkyPulse** [NamelessMC/Nameless#184] opened 2016-05-03 00:17 UTC
I am having a problem where my server does not show as online on the play tab. When I am on it, also within the infractions it gives me this error when i try and go to it when I know my login info is correct that I put in the Database fields. 

`SQLSTATE[28000] [1045] Access denied for user 'endermite_***'@'***.*.*.*' (using password: YES)
Please check your database connection settings.`

* being numbers the ip and username, just blanked them out.

**Comment by samerton** [comment] 2016-05-03 08:34
With your server not appearing as online, this may be an issue with your web host; in that case, you may have to use the external query (AdminCP -> Minecraft), can you see if that helps at all?

As for the MySQL, ensure remote hosts are enabled within MySQL and that your website's IP address has access to connect to the MySQL database.

**Comment by SkyPulse** [comment] 2016-05-03 20:21
Okay, ill try that. I have ran into a big problem. I put on a custom background in the css. When I go to www.skypulse.us it won't show. But when I go to skypulse.us it will. Do you think this has something to do with cloudflare?

**Comment by SkyPulse** [comment] 2016-05-03 20:26
Also, it logs my account is not logged in on the www. one.

**Comment by SkyPulse** [comment] 2016-05-03 20:52
I am using the SQL Database that came in MultiCraft. Will that not work?

**Comment by samerton** [comment] 2016-05-03 20:59
Looking at your CSS, there's no background image defined. As you say, it could be due to Cloudflare's caching, in which case it's best to purge the cache within your Cloudflare control panel.

As for your logged in account, this is due to the www and non-www sessions being separate. In this case, it's best to force a redirect from www to non-www, or vice versa. Try replacing the contents of **.htaccess** with [these rules](https://gist.githubusercontent.com/samerton/67ed1e03504c109a5d6a4381028b526d/raw/9c0f7428fede19ef0f6f0ed19aefd04ce8029b50/.htaccess) (untested, back up the existing .htaccess first in case you experience issues).

As for the SQL database that comes with Multicraft, that should work yes. One potential issue is that your MySQL settings (depending on how it's set up, I'm not too sure about this) may have the "bind-host" option to localhost for security reasons; if your website is hosted on another machine this needs disabling. There are steps on doing this (if you have access to the MySQL configuration and you're not using a shared Minecraft host) in [this post](http://stackoverflow.com/a/32716003).

**Comment by SkyPulse** [comment] 2016-05-03 22:42
Yep my bad, the image wasn't in the css. (enabled different theme) The reason it was because I need to clear browser data such as cached images. I'm using a shared host. How would I do it with a shared host then?

**Comment by samerton** [comment] 2016-05-03 22:56
It won't be possible to change your MySQL settings using a shared host. Generally, they already allow remote access, so unfortunately I can only recommend you double check the MySQL settings you inputted into the infractions settings.

**Comment by Schwertspize** [comment] 2016-05-04 05:44
@SkyPulse that depends on your shared host. 

As I experienced, they don't allow direct access from outside (but from a ssh tunnel of course) but yeah, check the config file (html/core/config.php I think)

**Comment by SkyPulse** [comment] 2016-05-04 22:34
I don't have access to the config. I am using multi-craft SQL Database. I suppose I can use a SQL database from my website cpanel and do one there. I did try it, but not with the things I have been told to to above. Right now my provider is helping me get access to it because something came up with an error after I changed the theme and it just gives me errors when I try and access it.

**Comment by SkyPulse** [comment] 2016-05-05 02:27
Also, my discord module is not loading. It just loads with the two cubes in the middle.

**Comment by Schwertspize** [comment] 2016-05-05 06:09
@SkyPulse regarding discord. That could be a discord issue, I experienced long loading times too, if you are a bit experienced in html/php/css you can just use my self-made one (it's mostly php)

https://gist.github.com/Schwertspize/77cc419386036aaa2ea45a3c541566a1

An example is on this site, I hope you don't care if the site is work-in-progress, discord seems finished to me

http://wob.qraut.alkaid.uberspace.de/servers/

**Comment by SkyPulse** [comment] 2016-05-05 19:10
Thanks! Ill try using that if Samerton doesn't have a fix for my current one.

**Comment by samerton** [comment] 2016-05-05 19:13
I can't find any issues with the existing Discord widget, the only thing I can think of is an invalid Discord server ID. 
Can you double check your inputted Widget ID matches the ID shown in the "Widget" tab of the Discord Server Settings modal?

**Comment by SkyPulse** [comment] 2016-05-05 22:11
Everything is put in correctly. This is my server id "176801755986657280" if you want to try it.

**Comment by samerton** [comment] 2016-05-05 22:16
I've taken a look, and I also get the same issue with your ID, however it works without issue with my own ID. I can only reproduce the issue if I insert an invalid server ID, so unfortunately I don't know what the problem you're experiencing is, I presume it's down to Discord itself.

**Comment by Schwertspize** [comment] 2016-05-06 09:31
Actually even my self written discord widget doesn't work, so i presume it's either an invalid server id or the widget is disabled. 

You can add me on discord: `guenstig werben#3669` (you can either add me as friend or send me a message)

**Comment by SkyPulse** [comment] 2016-05-06 12:24
Do you know if there is any permissions that I need to have set within Discord?

**Comment by Schwertspize** [comment] 2016-05-06 13:02
I don't know but I can take a look myself

Add friend:
![Add friend](https://cloud.githubusercontent.com/assets/11271600/15073731/8684cb24-139b-11e6-9455-dc5ed1f157d3.JPG)

**Comment by SkyPulse** [comment] 2016-05-06 19:06
Add friend on what?

**Comment by Schwertspize** [comment] 2016-05-06 21:22
Discord.... Did you even read my posts before that?

**Comment by SkyPulse** [comment] 2016-05-07 04:29
Yes sorry, didn't see the 2nd paragraph. I'll add you.

**Comment by samerton** [comment] 2016-05-13 11:30
I'll go ahead and close this as I don't believe these are issues with Nameless. If you're still having issues, feel free to re-open.

**Closed by samerton** 2016-05-13 11:30 UTC
Labels: question

**Comment by Schwertspize** [comment] 2016-05-13 12:03
The latter issue turned out that although we told @SkyPulse some times here it was required that I tell him on discord too, that his widget wasn't enabled. That explains, why my widget did fail too. I hope the original issue was resolved too
