### ISSUE TITLE
error when trying to log in via discord or google account, it gets endlessly loaded

### ISSUE THREAD

**Issue by CursedStudios-LA** [NamelessMC/Nameless#2966] opened 2022-08-05 03:01 UTC
### Describe the issue

the log on the page only presents me with this error in the console `[2022-08-04, 22:51:49] /var/www/html/cache/templates_c/b047fea119c9f38ce3163cf8c9c83effc71c0401_0.file.login.tpl.php(36): count(): Argument #1 ($value) must be of type Countable|array, string given`, pls help me

### NamelessMC Version

2.0.0-pr13

### Screenshots

![pre](https://user-images.githubusercontent.com/108887239/182992537-d5fb8990-3362-4448-b55b-aad555ec4d18.PNG)

**Comment by PadowYT2** [comment] 2022-08-05 03:41
As you are you are using Nexus, disable the preloader in template settings to see the error

**Comment by CursedStudios-LA** [comment] 2022-08-05 04:28
![Captura](https://user-images.githubusercontent.com/108887239/183001624-5fa6da05-6153-4635-b795-6b49caf49f96.PNG)

it gives me this error

**Comment by supercrafter100** [comment] 2022-08-05 06:41
This is mostlikely an issue with the template. Looking at the stack trace. If you could check if this issue still occurs when you have defaultrevamp enabled, since that is the default template. 

If it works fine on there, contact the template authors on their respective GitHub / discord

**Comment by PadowYT2** [comment] 2022-08-05 07:07
Btw, cannot reproduce this on Nexus:
https://user-images.githubusercontent.com/71085027/183021680-ba8f2e57-69b0-4f2c-87e7-bfba6690d8f6.mp4

**Comment by supercrafter100** [comment] 2022-08-13 07:09
Seeing as there has been no reply to this I’m guessing it has been fixed in v2.0.x

**Closed by supercrafter100** 2022-08-13 07:09 UTC
Labels: bug
