### ISSUE TITLE
Bypassing Page when Maintenance mode activate

### ISSUE THREAD

**Issue by NorgePlayz** [NamelessMC/Nameless#2610] opened 2022-02-24 06:34 UTC
### Describe the feature

When my website is down for maintenance, so we should ability to adding whitelisted URL so people can read some information like rules, apply etc

**Comment by Aberdeener** [comment] 2022-02-24 06:39
Duplicate of #2365 - please search for issues before making a new one.

**Closed by Aberdeener** 2022-02-24 06:39 UTC
Labels: enhancement
