### ISSUE TITLE
Invalid API method

### ISSUE THREAD

**Issue by BennyPlayzz** [NamelessMC/Nameless#838] opened 2017-10-22 01:37 UTC
Invalid API method.
Whenever I put my API key into the minecraft plugin and restart the server, it says "invalid api key". I have tried many times to sort it out (generating a new API key)

Version: 1.0.17
Plugin Version: pre-1.1

Screenshot of console: https://imgur.com/a/fQcGY

**Comment by H4nSolo** [comment] 2017-10-22 09:43
did you activate the API in the adminCP on you nameless Website?

**Comment by BennyPlayzz** [comment] 2017-10-22 10:50
Yes I did.
I even turned it on and off multiple times hoping it would work lmao

**Comment by Derkades** [comment] 2017-10-23 21:25
Did you set your api url correctly?

**Comment by BennyPlayzz** [comment] 2017-10-23 22:59
Yes, I did. I will try it again.

**Comment by BennyPlayzz** [comment] 2017-10-23 23:17
Scratch that. Still didn't work ;-;

**Comment by samerton** [comment] 2017-10-26 18:43
Would you be able to send me a link to your website, along with your API key, either via a private message on Discord (you can find the Nameless Discord [here](https://discord.gg/J6QsVaP)), or on Spigot (my profile is [here](https://www.spigotmc.org/members/samerton.10676/))?

**Comment by BennyPlayzz** [comment] 2017-10-28 12:16
Nothing worked, don't worry about it guys, but thanks for your help.

**Comment by Derkades** [comment] 2017-10-29 09:50
It looks like you have a proxy or something else that is changing the text on the page, resulting in the plugin not being able to parse it. Since this is related to your setup and not a bug in the plugin, I am going to close this issue. If you have other issues feel free to create a new issue here: https://github.com/NamelessMC/Nameless-Plugin

**Closed by Derkades** 2017-10-29 09:50 UTC
