### ISSUE TITLE
gifs aren't working

### ISSUE THREAD

**Issue by Jojo1542** [NamelessMC/Nameless#1188] opened 2018-08-06 01:29 UTC
* What kind of issue is it (Question, Bug, etc.)? 
Question
* In which version of NamelessMC did it occur (1.x.x)?
1.0.21
* How would you describe the issue?
In my forum, gifs aren't working (profile pics)
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Yes
![image](https://user-images.githubusercontent.com/31800809/43692576-ee7d70b8-9928-11e8-9842-e0bf3fc6ed4f.png)
* Do you have an idea how or where the issue occurs?
When i change my Profile Pic to a Animated GIF
* What Modules are you using ?
Default Modules
* What theme are you using ?
TriihardTHEME

**Comment by samerton** [comment] 2018-08-06 16:57
Hi,

In version 1, this issue is caused by the way images are uploaded.

Version 2, which is still in development, has fixed this problem however as a result it requires a slightly newer PHP version of 5.4+.

Unfortunately I don't think the issue will be fixed in version 1, only the upcoming v2 release.

**Comment by samerton** [comment] 2018-08-19 12:55
I'll mark this as closed since v2 has gif support already.

**Closed by samerton** 2018-08-19 12:55 UTC
