### ISSUE TITLE
Changing the size of an image doesn't update it upon saving.

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [NamelessMC/Nameless#3501] opened 2024-04-01 18:31 UTC
### Describe the issue

Basically if you insert an image (idk about local, I only used external ones from imgur), you adjust the image size, press save, click the image again, the size is what you typed in, but as soon as you update/post the post, the image is in a different format (I assume the original size), if you edit the post and check the image, it always resets the size of it to 1200w 350h, even tho the image is clearly not that size.

### NamelessMC Version

2.1.0

### To Reproduce

Create a new post
Insert image via link (or local idk about that one)
Adjust the size
save the image popup > click again to confirm the values are correct.
post your post
image is in different size (I believe in the original size)
edit post > check image >values will be 1200w 350h

### Expected Behaviour

I expect it to work and resize the input image/link correctly.

### Screenshots

Before changing: https://prnt.sc/cyhs8obKGOSE
Changed to the said values and pressing safe: https://prnt.sc/HJpNteaA5yd7
then it looks like this, which for sure is not the input size: https://prnt.sc/bUia8GYS8WCy
If I then edit the post again and check the image size it is back to 1200w and 350h https://prnt.sc/sq_y4uULa1ok

### Additional Information

I could only pick 2.1.0 in version but it is Version 2.1.2.

**Comment by samerton** [comment] 2024-06-08 15:06
I've not been able to reproduce this one either in the forum or on a custom page - the size is correctly saving for me (using latest development code). Perhaps it has been fixed since 2.1.2, meaning 2.2.0 will resolve this issue.

**Comment by samerton** [comment] 2024-12-01 14:52
I will mark this as closed on the assumption that it will be resolved in 2.2.0. If this is not the case, feel free to leave a comment against this issue and I can open it again.

**Closed as not planned by samerton** 2024-12-01 14:52 UTC
Labels: bug, cannot reproduce
