### ISSUE TITLE
Option to Disable Contact Page

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#2260] opened 2021-05-07 19:23 UTC
It would be nice if there was an option in StaffCP to disable the contact page and remove the contact icon from the footer.
Pretty easy to implement as far as I know.

**Comment by partydragen** [comment] 2021-05-07 21:45
My idea is to remove the Contact Us page as people can use the Forms Module instead and the Contact Us page can come as pre-setuped form in the Forms module

Forms module is much more configurable it only missing the feature to send email like contact us do but that should be pretty easy feature to add, Many using the Forms module anyways

**Comment by partydragen** [comment] 2021-05-08 12:26
> > My idea is to remove the Contact Us page as people can use the Forms Module instead and the Contact Us page can come as pre-setuped form in the Forms module
> > Forms module is much more configurable it only missing the feature to send email like contact us do but that should be pretty easy feature to add, Many using the Forms module anyways
> 
> I'm not sure if it has g / hcaptcha, but it would be useful.

it was added a few months ago

**Comment by Jochyoua** [comment] 2021-05-12 09:48
Is the contact email really required information? It could be implemented that if left empty the contact portion would be disabled and not shown to users

**Comment by CqldFire** [comment] 2021-05-12 15:04
> Is the contact email really required information? It could be implemented that if left empty the contact portion would be disabled and not shown to users

That would be a great idea.

**Comment by Aberdeener** [comment] 2021-06-08 20:24
> Is the contact email really required information? It could be implemented that if left empty the contact portion would be disabled and not shown to users

Looked into this, the contact email is also used for forum topic reply emails and mass emailing - so this would not quite be the best option. 

I'll make this an on/off toggle as originally proposed for now.

**Comment by PikaMug** [comment] 2021-12-27 01:35
Has this been implemented yet and, if so, where in the Admin Panel?

**Comment by Aberdeener** [comment] 2021-12-27 01:44
The issue is still open so no it hasn't been implemented 😛

**Comment by partydragen** [comment] 2021-12-27 01:51
Current solution is to use Forms module, then create a form with the url /contact that will override the page

then you can either reject it completly with the permissions or setup it by using the Forms module

**Comment by PikaMug** [comment] 2021-12-27 02:00
> The issue is still open so no it hasn't been implemented 😛

Thanks. The last sentence of your prior comment made me think you might've done it and forgot to close this.

> Current solution is to use Forms module, then create a form with the url /contact that will override the page

What if having a contact/form isn't desired at all? I suppose one could create a blank page with that url but at that point there really ought to just be a toggle, no?

**Closed** 2022-02-18 16:53 UTC
Labels: enhancement
