### ISSUE TITLE
API Not working - Reminder

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#424] opened 2016-09-28 16:09 UTC
API Not working this is just a reminder so u remember to take a look :P

**Comment by AlliedCore** [comment] 2016-09-28 19:35
In what aspect do you mean by the API is broken or not working?

**Comment by partydragen** [comment] 2016-09-28 19:52
Its the Actions on api who not working its always stand Invalid API method

Self it are correct so Samerton wanted to take look at the API
So this issuse is just a reminder så him Remember to take a look and then fix it

**Comment by samerton** [comment] 2016-09-28 23:27
I've not been able to take a look recently, but I'm fairly certain it's an issue with the POST request your test plugin's been using as opposed to an issue with the API itself, as I did a fair bit of testing back before it came out.

**Comment by samerton** [comment] 2016-10-04 14:13
I've just experimented with the API, and I can confirm it works as intended.
I'll close this issue, and respond to the private messages over on Spigot.

**Closed by samerton** 2016-10-04 14:13 UTC
