### ISSUE TITLE
Changing profile settings with Friendly URLs on doesn't redirect correctly

### ISSUE THREAD

**Issue by bippityboopity** [NamelessMC/Nameless#1631] opened 2020-04-06 12:33 UTC
**Describe the issue**
So lets say my forum is located at example.com/forums. So if I go to change a setting on my profile, for example my email, and I click confirm, with Friendly URLs on - it redirects me to "example.com/*profile-settings-url*" instead of "example.com/forums/*profile-settings-url*".

**To Reproduce**
Steps to reproduce the behaviour:
1. Install forum into folder that isn't root.
2. Enable Friendly URLs.
3. Change profile setting.
4. **Observe.**

**Expected behaviour**
It redirects me to the correct directory, instead of the root folder of the site.

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Comment by samerton** [comment] 2020-04-11 09:47
Strangely not able to reproduce this one, tried with the top section (eg changing nickname) and also changing email address, but it's correctly redirecting me back to the subdirectory path with friendly URLs on.

**Comment by samerton** [comment] 2020-04-20 18:49
Should be fixed by https://github.com/NamelessMC/Nameless/commit/d184753f0a7ea3fa8340b72baa4fb3dafba5c7f1

**Closed by samerton** 2020-04-20 18:49 UTC
Labels: bug, v2
