### ISSUE TITLE
Google Analytics inbuild

### ISSUE THREAD

**Issue by NorgePlayz** [NamelessMC/Nameless#1983] opened 2020-12-26 05:21 UTC
It's much faster and saving more time to figure it out how to put the code in the templates and asking for help. Adding in it will doing so much faster and saving alot of time

**Comment by Derkades** [comment] 2020-12-26 09:08
Duplicate of https://github.com/NamelessMC/Nameless/issues/1941

**Closed** 2020-12-26 09:09 UTC
