### ISSUE TITLE
Indication of banned status on profile

### ISSUE THREAD

**Issue by cpkOfficial** [NamelessMC/Nameless#2058] opened 2021-01-18 17:18 UTC
Here is what I mean... Lets say you decide to Ban or even IP Ban a user on your site. After observing on the official NamelessMC website I noticed it doesn't indicate when people are banned. It shows their profile as normal. I think it would be neat if players names were either greyed out or an icon was added indicating they were banned. Hopefully this makes sense... ¯\_(ツ)_/¯

**Comment by samerton** [comment] 2021-01-19 10:12
Possible duplicate of https://github.com/NamelessMC/Nameless/issues/896

**Closed** 2021-02-24 22:11 UTC
Labels: duplicate, enhancement
