### ISSUE TITLE
Language file error

### ISSUE THREAD

**Issue by AltijdSander** [NamelessMC/Nameless#549] opened 2017-02-12 13:48 UTC
### Template:
* What kind of issue is it (Question, Bug, etc.)?
 Bug
* In which version of NamelessMC did it occur (1.x.x)?
2.0.0
* How would you describe the issue? 
When i configure the website, it wil say an error:

"Error loading language file general.php in Core"
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?

It will say: "Error loading language file general.php in Core" add my homepage

* Do you have an idea how or where the issue occurs?

In the general.php :P

**Comment by samerton** [comment] 2017-02-12 15:42
Have you selected a custom language through the AdminCP?

**Comment by samerton** [comment] 2017-03-12 13:30
Were you able to resolve the issue @AltijdSander?

**Comment by samerton** [comment] 2017-04-07 17:06
I'll mark this as closed as I can't reproduce any issues.

**Closed by samerton** 2017-04-07 17:06 UTC
