### ISSUE TITLE
Admin-backend doesn't load - 504 Gateway Timeout

### ISSUE THREAD

**Issue by OscarWoHA** [NamelessMC/Nameless#472] opened 2016-11-13 19:13 UTC
**What kind of issue is it (Question, Bug, etc.)?** This is a bug.
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.13
**How would you describe the issue?** The admin backend doesn't load at all. Just getting a 504 Gateway time-out error.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** No, unfortunately there aren't any error-messages while trying to browse nor in the logs.
**Do you have an idea how or where the issue occurs?** Dunno, really have no clue.

**Comment by samerton** [comment] 2016-11-13 19:25
Can you navigate straight to a different section of the AdminCP via the URL, for example yoursite.com/admin/core?

If so, and you're using web hosting as opposed to a VPS/dedicated machine, this could be your web host blocking the file_get_contents function.

**Comment by OscarWoHA** [comment] 2016-11-13 19:26
I am using a dedicated server, and no, it doesn't let me load any of the sublinks under admin/

**Comment by samerton** [comment] 2016-11-13 19:35
Unfortunately I'm not sure what the issue could be, this isn't something I've seen occurring before.

Is this happening on a new installation, or has the admin panel worked in the past?
Also, are you running Apache or nginx?

**Comment by OscarWoHA** [comment] 2016-11-13 19:39
This is an installation that has been working for a couple of weeks. I am running Nginx. It seems like the problem only occurs in the Overview-page of the Admin-panel.

**Comment by OscarWoHA** [comment] 2016-11-13 19:39
Link to the installation:
https://trulscraft.no/

**Comment by partydragen** [comment] 2016-11-13 19:48
Oh, Your a staff from TrulsCraft? :P

**Comment by samerton** [comment] 2016-11-13 19:52
@OscarWoHA 
Can you try replacing the contents of **pages/admin/index.php** with [this code](https://gist.githubusercontent.com/samerton/31d3d684ba3f88a77ebe0c46082aa080/raw/566bf768a76502e5f705d6ab2632a221376910ae/index.php)?
I've removed the update checker, hopefully it might help with your issue.

**Comment by OscarWoHA** [comment] 2016-11-13 20:00
That perfectly solved the problem, and yes, @partydragen I am head developer and system administrator at TrulsCraft.

**Comment by samerton** [comment] 2016-11-13 20:02
Glad to hear the issue is resolved, I'll look into implementing a "proper" fix for this for the next release.

**Comment by OscarWoHA** [comment] 2016-11-13 21:08
We'll be happy to host something for the project if you need anything.

**Comment by Fellings1** [comment] 2016-11-14 13:35
@partydragen Please keep comments on topic to the issue.

**Comment by Fellings1** [comment] 2016-11-15 11:00
I'm assuming the issue no longer persists, so I'll close the issue.

**Closed by Fellings1** 2016-11-15 11:00 UTC
