### ISSUE TITLE
Announcements StaffCP Link Issue

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1879] opened 2020-10-20 15:31 UTC
**Describe the issue**
Please describe the issue in as much detail as possible

When you click on the announcements page in staffcp (latest dev code), the active class is not added.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest dev code version of nmc
2. Go to staffcp
3. Click on "Announcements"

**Expected behaviour**
What were you expecting to happen?

I was expecting the active class to be added to the nav link, like what happens with all other staffcp pages

**NamelessMC version (from AdminCP -> Overview)**

2.0.0 pre-7 latest dev code

**Comment by Aberdeener** [comment] 2020-10-20 15:32
Unable to reproduce. 
On both v2 and api-changes this works fine for me

**Comment by Aberdeener** [comment] 2020-10-21 05:15
Nevermind, I dont know how i didnt notice this. 
Thank you for pointing it out, fixed in 76eabc0

**Closed by Aberdeener** 2020-10-21 05:15 UTC
