### ISSUE TITLE
Fail to install properly.

### ISSUE THREAD

**Issue by Dragonrage372** [NamelessMC/Nameless#889] opened 2017-12-10 09:23 UTC
### Template:
* What kind of issue is it (Question, Bug, etc.)?
failed to install properly
* In which version of NamelessMC did it occur (1.x.x)?
latest 1.0.19
* How would you describe the issue?
right after i created the Admin account it popped up an error then vanished before i could read it then it tried to go to the home page just says 404 .
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
logs can not be placed due to having some ids in it that aren't allowed to be given.
Here is the image of the main page that its trys to take me to after the install. [https://imgur.com/CMH3I4u]

* Do you have an idea how or where the issue occurs?

not sure when.

**Comment by samerton** [comment] 2017-12-10 11:03
The solution to the 404 issue can be found [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache).

**Comment by samerton** [comment] 2017-12-10 11:03
Looking at your screenshot, the problem is that the Nameless files are in the "Nameless-1.0.19" folder.

If you move all files from inside this folder out into the "public_html" folder, the issue should be fixed.

**Comment by Dragonrage372** [comment] 2017-12-10 11:05
I fixed it by installing 2.0.0 pre3 , so u can mark it as fixed if u can or i have to do that.

**Comment by Dragonrage372** [comment] 2017-12-10 11:06
well the hosting company i use don't want you to put anything outside a folder in the public_html since i'm using an unstable machine that they are wanting some of they're beta testers to test.

**Comment by samerton** [comment] 2017-12-10 11:14
Glad version 2 has resolved the problem.

**Closed by samerton** 2017-12-10 11:14 UTC
Labels: question
