### ISSUE TITLE
Cookie design fail

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2660] opened 2022-04-02 05:36 UTC
### Describe the issue

On mobile the dark popup of the "Cookies" is pure dark and dark text on dark popup

### NamelessMC Version

From commit 76713ba

### To Reproduce

1. Go on mobile or turn on "Toggle device toolbar" in browser console
2. Reload the page
3. See the problem

### Expected Behaviour

Should be white on dark

### Screenshots

![https://cdn.padow.ru/PL5s](https://cdn.padow.ru/PL5s)

**Comment by samerton** [comment] 2022-04-02 12:52
Unable to reproduce on latest v2
<img width="140" alt="Screenshot 2022-04-02 at 13 51 51" src="https://user-images.githubusercontent.com/1812544/161384181-b1cff02b-8e3c-4b2d-bffd-ee5d9fa0f118.png">

**Comment by PadowYT2** [comment] 2022-04-02 13:03
What browser & resolution do you have?
I have
* 390x844 (example resolution, there are a lot)
* Google Chrome 99.0.4844.82 (Official Build) (64-bit)
https://user-images.githubusercontent.com/71085027/161384578-b4b71d32-800f-49f0-897b-d1f21d420087.mp4

**Comment by samerton** [comment] 2022-04-02 13:10
I've tried with Chrome + Safari on a variety of resolutions, including the one you mention.

Could you please right click -> inspect element on the cookie text to see what's determining the text colour? The following CSS should apply:
```css
.cc-revoke.cc-bottom.cc-right.cc-animate {
    color: #fff;
}
```
(from https://github.com/NamelessMC/Nameless/blob/4b4fe73b552f95d4b0e89e7b88acac23c4bc82c9/custom/templates/DefaultRevamp/css/custom.css#L601-L603)

**Comment by PadowYT2** [comment] 2022-04-02 13:26
> I've tried with Chrome + Safari on a variety of resolutions, including the one you mention.
> 
> Could you please right click -> inspect element on the cookie text to see what's determining the text colour? The following CSS should apply:
> 
> ```css
> .cc-revoke.cc-bottom.cc-right.cc-animate {
>     color: #fff;
> }
> ```
> 
> (from
> 
> https://github.com/NamelessMC/Nameless/blob/4b4fe73b552f95d4b0e89e7b88acac23c4bc82c9/custom/templates/DefaultRevamp/css/custom.css#L601-L603
> 
> )

By removing background-color, you can see it is dark
![https://cdn.padow.ru/flBn](https://cdn.padow.ru/flBn)

**Comment by samerton** [comment] 2022-04-02 13:30
> By removing background-color, you can see it is dark ![https://cdn.padow.ru/flBn](https://camo.githubusercontent.com/5249b7f8a49b2ea9e22b822bb43d96e95768cadd2bcc361f17879c5d3eba09b5/68747470733a2f2f63646e2e7061646f772e72752f666c426e)

I've just had a look at your site using the URL in your video, and the text is coloured white as expected on my side. I have no idea why it wouldn't be the case for you - I'm assuming you've cleared browser cache etc?

Could you open up your Default Revamp template's css/custom.css file in your browser, to check the CSS mentioned in my above reply is present

**Comment by PadowYT2** [comment] 2022-04-02 13:31
> 

Yep, I cleared cookies. The css exists in the file

**Comment by samerton** [comment] 2022-04-02 13:35
I wonder why your browser isn't picking up on it then. I'll wait to see if anyone else experiences the same issue.

**Comment by Browsit** [comment] 2022-04-03 11:31
Unable to replicate on Chrome (99.0.4844.84), iOS (14.8.1), or Android (11). Try an Incognito window without browser extensions?

**Comment by PadowYT2** [comment] 2022-04-04 11:50
> Unable to replicate on Chrome (99.0.4844.84), iOS (14.8.1), or Android (11). Try an Incognito window without browser extensions?

I cannot answer this right now, but I will when https://canary.discord.com/channels/246705793066467328/280489551213101056/960496452298223666 is fixed

**Comment by PadowYT2** [comment] 2022-04-05 07:36
> Unable to replicate on Chrome (99.0.4844.84), iOS (14.8.1), or Android (11). Try an Incognito window without browser extensions?

Just reinstalled, viewing with Incognito with **absolutely no**  extensions. Maybe a video on your end?

**Comment by Derkades** [comment] 2022-04-05 09:55
Cannot reproduce in firefox on current latest user-integrations branch

**Comment by PadowYT2** [comment] 2022-04-05 10:37
> Cannot reproduce in firefox on current latest user-integrations branch

This also happens on firefox
https://user-images.githubusercontent.com/71085027/161736230-f6aaf5da-eb8a-4c69-af9c-ea7eefddede0.mp4

**Comment by Derkades** [comment] 2022-04-05 20:39
I can indeed reproduce it now but only when using developer tools "Device emulation"

**Comment by samerton** [comment] 2022-04-16 17:23
If it only occurs using developer tools then I don't think it's an issue for us to fix - I'll close this issue until it's reproducible using a device without developer tools

**Closed by samerton** 2022-04-16 17:23 UTC
Labels: bug, cannot reproduce

**Comment by PadowYT2** [comment] 2022-04-17 08:54
> If it only occurs using developer tools then I don't think it's an issue for us to fix - I'll close this issue until it's reproducible using a device without developer tools

But it happens on the phone too
https://cdn.discordapp.com/attachments/940614126676353034/965173453906911282/SVID_20220417_165420_1.mp4
