### ISSUE TITLE
Problems with MinecraftMarket integration.

### ISSUE THREAD

**Issue by Fiiily** [NamelessMC/Nameless#133] opened 2016-03-17 21:10 UTC
It 404's when you enter your username in MinecraftMarket. I've got a feeling MinecraftMarket is outright unable to have direct links to packages.

**Comment by samerton** [comment] 2016-03-24 13:50
I'm unable to reproduce any issues, if the issue you're experiencing only occurs after inputting the username, it's worth checking that your "Donation Plugin" setting is set to "MinecraftMarket" within the AdminCP -> Addons -> Settings tab, as otherwise the URL submitted will be incorrect.

**Comment by samerton** [comment] 2016-03-28 12:41
I'm going to go ahead and close this issue as it seems to work without issue on my end, if you're still experiencing issues feel free to reopen this.

**Closed by samerton** 2016-03-28 12:41 UTC
