### ISSUE TITLE
reCAPTCHA v3

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#3056] opened 2022-08-27 08:35 UTC
### Describe the issue

On my side the recaptcha v3 does not always work an error message "Invalid reCAPTCHA response." However, the keys are well informed and the domain name is well added to the recaptcha.

### NamelessMC Version

2.0.0

### To Reproduce

1. Go to login page
2. Enter your login (Mail and Password)
3. Click on login

### Screenshots

![image](https://user-images.githubusercontent.com/12797827/187022374-12ff4bc9-af8a-404d-8649-e0080f10d751.png)

**Comment by PadowYT2** [comment] 2022-08-27 08:41
Cannot reproduce on Cobalt 1.6.0 & NamelessMC 2.0.2. You probably missplaced Site Key & Secret Key (like Site Key from Admin Console to Secret Key on your website)

**Comment by CreaCloudz** [comment] 2022-08-27 08:47
Precisely no I come to recreate a key and I still have this problem and yet it is auth I did a vardump which returns me the captcha it is the validation that is blocking ....

**Comment by PadowYT2** [comment] 2022-08-27 08:49
Could you see if this is a problem with DefaultRevamp?
**If it is:**
Could you show your key settings (in Admin Console)?
Could you say what URL is in StaffCP > Configuration > Api?

**If it is not:**
Update Cobalt

**Comment by CreaCloudz** [comment] 2022-08-27 08:56
It works with DefaultRevamp

![image](https://user-images.githubusercontent.com/12797827/187023114-51141c5a-4874-4119-886c-25cf950bb8c4.png)
Key dev

URL : https://**.fr/index.php?route=/api/v2
And cobalt is in latest version already

**Comment by PadowYT2** [comment] 2022-08-27 09:02
> It works with DefaultRevamp
> 
> ![image](https://user-images.githubusercontent.com/12797827/187023114-51141c5a-4874-4119-886c-25cf950bb8c4.png) Key dev
> 
> URL : https://**.fr/index.php?route=/api/v2 And cobalt is in latest version already

What version is your Cobalt? Also remove the keys right now

**Comment by PadowYT2** [comment] 2022-08-27 09:05
Nevermind, my bad, it is Cobalt's fault, forgot to enable the actual Captcha, close the issue and already reported to Drew.

**Comment by CreaCloudz** [comment] 2022-08-27 09:07
No problem, did you report it now?

**Closed as not planned** 2022-08-27 10:36 UTC
Labels: bug, third party
