### ISSUE TITLE
Automatic promotion based on website activity

### ISSUE THREAD

**Issue by MinecraftHDKIll** [NamelessMC/Nameless#2094] opened 2021-02-07 18:56 UTC
In sometime,after members get active on forums and other stuff,they will get "Well-Known Member" group. My request is: you should add option for groups when someone is active on forums in some time they will get Well Known Member or some group.

**Comment by Derkades** [comment] 2021-02-14 12:30
Duplicate of #173

**Closed by Derkades** 2021-02-14 12:30 UTC
Labels: enhancement
