### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by mani1232** [NamelessMC/Nameless#2833] opened 2022-06-06 16:14 UTC
### Describe the issue

Why are all settings reset when they are changed and the "apply" button is pressed, but the setting itself changes, to see this you need to reload the page again

### NamelessMC Version

2.0.0-pr13

**Comment by PadowYT2** [comment] 2022-06-06 16:15
Where does this exactly happen?

**Comment by PadowYT2** [comment] 2022-06-06 16:17
I can reproduce this on general settings only

**Comment by mani1232** [comment] 2022-06-06 16:17
Another example: in the section "Layout" -> "Images" - there is a visual bug

**Comment by mani1232** [comment] 2022-06-06 16:18
![image](https://user-images.githubusercontent.com/70480001/172201873-3baeaf74-64ef-4209-a253-29497b931c3d.png)

I select 1 photo, but it shows the selected second

**Comment by mani1232** [comment] 2022-06-06 16:20
And how do I fix it, everything seems to be working fine
![image](https://user-images.githubusercontent.com/70480001/172202278-6e05ccce-7f6c-4ef6-8746-9313a00b183b.png)

**Comment by partydragen** [comment] 2022-06-06 17:58
> ![image](https://user-images.githubusercontent.com/70480001/172201873-3baeaf74-64ef-4209-a253-29497b931c3d.png)
> 
> I select 1 photo, but it shows the selected second

Fixed in https://github.com/NamelessMC/Nameless/commit/2a2c3ddda5e8217187a0163822d9cfa8736048a5

**Comment by Aberdeener** [comment] 2022-06-09 03:59
Cannot reproduce

**Closed by Aberdeener** 2022-06-09 03:59 UTC
Labels: bug
