### ISSUE TITLE
Some buttons require clicking twice

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#308] opened 2016-07-06 16:49 UTC
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.10.  
**How would you describe the issue?** Some buttons, such as the forum post "Submit" button or the "Add/Remove Friend" button, don't work the first time they're clicked and instead reload the page. Clicking them a second time works.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Video: https://i.gyazo.com/bbe004e625d3fdc50d4c6482a2910565.mp4
**Do you have an idea how or where the issue occurs?** I think it happens mostly when multiple tabs are open with the website loaded, such as multiple profiles open in separate tabs while trying to add or remove friends.

**Comment by PugaBear** [comment] 2016-07-07 01:19
I can confirm that it only happens when you have multiple tabs open. Caused by the issue explained in #189 most likely

**Comment by samerton** [comment] 2016-07-07 23:11
As @PugaBear says, this is caused by invalid form tokens. I'm going to modify form tokens at some point in the future to support multiple tabs/windows, I'll close this and use #189 as the main discussion.

**Closed by samerton** 2016-07-07 23:11 UTC
