### ISSUE TITLE
Infractions

### ISSUE THREAD

**Issue by BrainRTP** [NamelessMC/Nameless#661] opened 2017-06-10 21:07 UTC
Hello! How it fix?
Notice: Undefined index: name in /home/servers/web/xxx/public_html/core/integration/uuid.php on line 83
Notice: Undefined index: id in /home/servers/web/xxx/public_html/core/integration/uuid.php on line 83
Notice: Undefined index: properties in /home/servers/web/xxx/public_html/core/integration/uuid.php on line 83
Use BanManager

**Comment by ThatTonybo** [comment] 2017-06-16 00:43
@BrainRTP what plugin are you using?

**Comment by samerton** [comment] 2017-06-21 14:04
I'll mark this as closed as it's an issue with the server communicating with Mojang's API, the issue is usually resolved automatically after a while, or the notices can be hidden by disabling error reporting in the AdminCP -> Misc tab.

**Closed by samerton** 2017-06-21 14:04 UTC
