### ISSUE TITLE
How would I add in a new page (like Play)?

### ISSUE THREAD

**Issue by xBreaksx** [NamelessMC/Nameless#183] opened 2016-05-01 22:17 UTC
Hi again, I am wondering how I would go about making a new page to display my stats for a game that has website stats support, but requires you to make a new .php file and insert it into your webserver. How would I do this?

Here is what I'm trying to add in and the directions it's telling me to follow (which won't work): http://dev.bukkit.org/bukkit-plugins/bedwars/pages/website-stats/

Thanks for your help!

**Comment by samerton** [comment] 2016-05-01 23:07
Hi,

Simply uploading the stats.php file that page mentions to the **pages** directory will make the page available through your-site.com/stats.

Then, you can use a bit of trickery, and create a new custom page (AdminCP -> Custom Pages) with the "Page URL" field being **/stats*, and you'll have a link in your navbar.

**Comment by xBreaksx** [comment] 2016-05-02 22:00
So I managed to get those website stats working, but we just converted to a "Reloaded" version of the plugin that was found on Spigot (https://www.spigotmc.org/resources/bedwars-rel.6799/) and it has a completely different way of doing webstats (https://github.com/Yannici/bedwars-reloaded-webstats/wiki/Instructions). Can you help me out with this? At the moment, the page where the stats are supposed to go is completely blank; nothing in the page source and inspect element.

Currently I have the downloaded webstats zip unpacked in a folder name "webstats" in pages.

**Comment by Schwertspize** [comment] 2016-05-03 05:40
Maybe I can take a look at the integration page and try to design a page which fits to namelessmc

**Comment by samerton** [comment] 2016-05-05 15:23
If you're still having an issue where the page is completely blank, can you check your server's Apache logs to see if there are any related errors in there? The location of the log varies depending on your configuration.

**Comment by xBreaksx** [comment] 2016-05-06 03:39
I don't know where to find my Apache logs. I've looked all over the place, but cannot find it.

**Comment by samerton** [comment] 2016-05-06 08:19
Looks like there's a MySQL issue as opposed to any other compatibility issues; can you double check your Bedwars MySQL details?

**Comment by xBreaksx** [comment] 2016-05-07 00:54
I actually have no idea what I did wrong on my Bedwars MySQL details. It's so vague.

Anyways, here's it is:
`<?php
/* 
  ____           _                          
 |  _ \         | |                         
 | |_) | ___  __| __      ____ _ _ __ ___   
 |  _ < / _ \/ _` \ \ /\ / / _` | '__/ __|  
 | |_) |  __| (_| |\ V  V | (_| | |  \__ \  
 |____/ \___|\__,_| \_/\_/ \__,_|_|  |___/_ 
 |  __ \    | |               | |        | |
 | |__) |___| | ___   __ _  __| | ___  __| |
 |  _  // _ | |/ _ \ / _` |/ _` |/ _ \/ _` |
 | | \ |  __| | (_) | (_| | (_| |  __| (_| |
 |_|  \_\___|_|\___/ \__,_|\__,_|\___|\__,_|
                                  by Yannici
 
 */

$config = array(
	'path' => 'arcadecraft.beastmc.com/mc103014:3306', // without slash
	'database' => array(
			'host' => '96.127.169.218',
			'user' => 'mc103014',
			'pw' => 'd275581255',
			'db' => 'mc103014'
	),
	'per-page' => 10,
	'order' => 'score',
	'direction' => 'DESC' // ASC (ascending) or DESC (descending)
);
?>`

**Comment by Schwertspize** [comment] 2016-05-07 08:41
# YOU SHOULD NEVER EVER POST PASSWORDS ON THE INTERNET

But the username, passwords and hosts are right, I was able to connect via command line

**Comment by xBreaksx** [comment] 2016-05-07 15:50
Terribly sorry about that, and thank you. Luckily I can regenerate the password. Once again, thank you though. 

Anyways, do you know what is going wrong for my attempt?

**Comment by Schwertspize** [comment] 2016-05-07 20:43
No sorry

**Comment by xBreaksx** [comment] 2016-05-09 22:46
Can I bump this? I still have no solution.

**Comment by samerton** [comment] 2016-05-13 11:28
I'll give this a go today, see if I can reproduce any issues.

**Comment by xBreaksx** [comment] 2016-05-15 01:56
Did you get anything to pop up?

**Comment by samerton** [comment] 2016-05-16 15:00
I didn't experience any issues, here's how I set it up:

- Moved the files to a folder named "bedwars" on the webserver (this can be anything, such as stats etc)
- Edited the config.inc.php, set the path to mysite.com/bedwars and filled in MySQL information

I could then access the webstats using mysite.com/bedwars and they loaded as expected.

**Comment by xBreaksx** [comment] 2016-05-17 00:46
I followed exactly what you did and got a blank page. Where should I put the bedwars folder? Pages? And it came up with an error log, saying exactly the same errors that I posted 11 - 12 days ago. I'm connecting to the database my multicraft provides, could that be it?

**Comment by samerton** [comment] 2016-06-14 22:58
@xBreaksx Sorry it's taken so long to get back to you, are you still experiencing the problem?

**Comment by samerton** [comment] 2016-08-18 16:36
I'll mark this as closed as I don't believe this is a Nameless issue as such, if you're still experiencing the issue feel free to re-open.

**Closed by samerton** 2016-08-18 16:36 UTC
Labels: question
