### ISSUE TITLE
Blank Site

### ISSUE THREAD

**Issue by Aviorleking** [NamelessMC/Nameless#954] opened 2018-01-20 21:08 UTC
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 2.0.0-pre.3
* How would you describe the issue? Blank site(user interface) + 503 error(AdminCP)
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? nothing in logs
* Do you have an idea how or where the issue occurs?
* (Added) Modules enabled ? Nextyle & Forum
* (Added) Theme used ?  Nextyle
After trying to send a test mail with PHPMailer
i wasn't able to use site for 2-4 minutes and after for 1-2 minutes got 503 error
After thats site came back normaly

**Comment by Derkades** [comment] 2018-01-20 22:04
So the issue is fixed now?

**Comment by Aviorleking** [comment] 2018-01-20 22:49
Trying back...

**Comment by Aviorleking** [comment] 2018-01-20 22:54
same 504 error 
console : 
`L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert.`
(nothing intersting)

**Comment by Aviorleking** [comment] 2018-01-20 23:01
i needed to change a value in DB : nl2_settings "phpmailer" from 1 to 0 to stop 504

**Comment by samerton** [comment] 2018-01-21 20:22
The problem's because you've enabled PHPMailer, and your SMTP details are incorrect (AdminCP -> Core -> Emails), so the request to your email server is timing out.

**Comment by Aviorleking** [comment] 2018-01-21 20:58
Shouldn't you test for details before trying to send test message ?

**Comment by samerton** [comment] 2018-01-21 20:59
The message is the test, sending the email will test the details are correct and log the error in the AdminCP -> Core -> Email -> Errors tab.

**Comment by Aviorleking** [comment] 2018-01-21 22:25
the error wasn't logged
but can't you test using this ?
https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps
and after send test mail ?

**Comment by samerton** [comment] 2018-01-21 22:26
I'd imagine you'd get the same issue with that script too, due to the timeout.

**Comment by Aviorleking** [comment] 2018-01-21 23:12
so why not just these lines : 
`
   // Check server connection
    if (!$smtp->connect('mail.example.com', 25)) {
        throw new Exception('Connect failed');
    }
//Check  user auth
    if (is_array($e) && array_key_exists('AUTH', $e)) {
        if ($smtp->authenticate('username', 'password')) {
            echo "Connected ok!";
        } else {
            throw new Exception('Authentication failed: ' . $smtp->getError()['error']);
        }
    }
`
it could be at least quick than 5 minutes

**Comment by samerton** [comment] 2018-01-22 08:34
I can definitely test it out, I *think* $smtp->connect might suffer from the same issue, but I could be wrong.

**Comment by samerton** [comment] 2018-04-22 16:16
I'll mark this as closed as there won't be any changes in the foreseeable future; the timeout is down to an incorrect SMTP connection address.

**Closed by samerton** 2018-04-22 16:16 UTC
Labels: question
